###
GET http://localhost:3000/admin/250
###
POST  http://localhost:3000/admin
Content-Type: application/json

{
    "login": "Samuel",
    "senha": "123456"
}
###
### 
PATCH http://localhost:3000/admin/1
###
### 
PUT http://localhost:3000/admin/1
###
### 
DELETE  http://localhost:3000/admin/1
###
### 
GET  http://localhost:3000/usuarios/3
###